### ISSUE TITLE
Norme tipografiche, incongruenze tra alcuni documenti (NdP e PdP)

### ISSUE THREAD

**Issue by AMike01** [SWEet16-SWE-Group/docs#140]
Nelle norme di progetto gli elenchi erano fatti così:

- item1: descrizione;
- item2: descrizione.

Nel piano di progetto invece come:

- **item1**: descrizione;
- **item2**: descrizione.

Notare il grassetto. Decidere una delle due norme tipografiche per evitare incongruenze

**Comment by AMike01** [comment]
Aggiungere stile del testo a NdP (sezione 3.1.6.2) ASAP

**Comment by IuliusSignorelli** [comment]
Teniamo la versione con il grassetto; non è meglio non mettere la punteggiatura negli item degli elenchi?

**Comment by AMike01** [comment]
> Teniamo la versione con il grassetto.

Ok va bene.
