### ISSUE TITLE
Caso d'uso dashboard ristoratore?

### ISSUE THREAD

**Issue by AMike01** [SWEet16-SWE-Group/docs#175]
Può essere sensato?

**Comment by IuliusSignorelli** [comment]
ma caso d'uso cosa intendi? tipo dove viene indirizzato un utente quando seleziona un profilo ristoratore?

**Comment by AMike01** [comment]
Caso d'uso: Visualizza dashbroad ristoratore
precondizioni: il ristoratore è connesso al sistema
postcondizioni: il ristoratore può gestire il ristorante (?)
scenario:
1. il ristoratore può accedere alle seguenti sezioni della dashboard: 

- prenotazioni (si veda uc)
- modifica informazioni ristorante
- lista ingredienti
- ecc.

Non so se sia sensato ripeto

**Comment by IuliusSignorelli** [comment]
allora sensato è sensato (le post condizioni potrebbero essere:il ristoratore visualizza la lista delle funzionalità di visualizzazione prenotazione,modifica profilo ecc...); tornerebbe al ristoratore quando vuole passare dalla gestione delle prenotazioni,alla modifica del profilo ecc e in ogni caso aggiunto questo useCase non serve modificare tutti gli altri già fatti

**Comment by AMike01** [comment]
Sarebbe da aggiungere diciamo che nelle precondizioni di tanti UC non bisognerebbe mettere "il ristoratore è connesso al sistema" ma "il ristoratore sta visualizzando la dashboard (si veda UCXY)"

**Comment by IuliusSignorelli** [comment]
Vero, aspettiamo che dice alex

Il giorno sab 2 mar 2024 alle ore 11:20 AMike01 ***@***.***>
ha scritto:

**Comment by bzn0u95quudr7jutfjap** [comment]
la dashboard del ristoratore sarebbe la visualizzazione delle prenotazioni divise per data

**Comment by AMike01** [comment]
quindi non va inserito come use case?

> la dashboard del ristoratore sarebbe la visualizzazione delle prenotazioni divise per data

**Comment by bzn0u95quudr7jutfjap** [comment]
> quindi non va inserito come use case?
> 
> > la dashboard del ristoratore sarebbe la visualizzazione delle prenotazioni divise per data

no è già apposto
