### ISSUE TITLE
Salvataggio di tutti gli UC in immagini all'interno di cartella uc_img

### ISSUE THREAD

**Issue by AMike01** [SWEet16-SWE-Group/docs#176]
Una volta fatto il merge di tutti i casi d'uso all'interno del documento, bisognerà fare gli screen di tutti i casi d'uso e salvarli all'interno della cartella uc_img (o altro nome, sceglie @bzn0u95quudr7jutfjap).
Un esempio di immagine è: facciamo lo screen del caso d'uso UC23-Condivisione prenotazione, su sfondo bianco dato da "use case object" su staruml, allora l'immagine si chiamera UC23.png/jpeg

Questo per semplificare l'aggiunta delle immagini al documento

**Comment by bzn0u95quudr7jutfjap** [comment]
cartella fai uc-imgs con il -

le immagini chiamale col formato : uc<numero>-<titolo>
numero è il numero dello use case
il titolo fallo tutto in minuscolo con - al posto degli spazi

**Comment by AMike01** [comment]
quindi ad esempio "uc-23.png"? oppure "uc-1.1.png"?

**Comment by bzn0u95quudr7jutfjap** [comment]
in caso di lettere accentate dai la lettera normale senza accento

**Comment by AMike01** [comment]
immagini salvate come `uc<num>.png`
