### ISSUE TITLE
validazione stilistica Analisid dei requisiti

### ISSUE THREAD

**Issue by bzn0u95quudr7jutfjap** [SWEet16-SWE-Group/docs#179]

**Comment by AMike01** [comment]
I nomi dei file hanno tutti una notazione omogenea tra di loro, dove la lettera iniziale è sempre
maiuscola e tutte le altre minuscole, e le parole sono spaziate da `_`, a cui viene poi aggiunta la versione `vX.Y.Z`.
Esempio: `Norme_di_progetto_v1.0.0`.

Viene fatta eccezione per i verbali dove il titolo è composto
semplicemente dalla data in cui si è svolto l’incontro più la versione. La data viene scritta in formato AAAA-MM-DD.

 Stile del testo
Gli stili del testo che vengono apportati all’interno di tutti i documenti sono:

Elenchi puntati o numerati : gli "item" cominciano con la lettera maiuscola e sono in grassetto, dopo i due punti (`:`) ci va una lettera minuscola.
Tutti gli item finiscono per `;`, tranne l'ultimo che termina per `.`
Ad es: 

Elenco 1:

- **Item1**: qualcosa;
- **Item2**: qualcosa.


● Sottolineato: utilizzato solamente per i link presenti nei documenti.
● Monospazio: utilizzato per riferimenti a codice.
