### ISSUE TITLE
Aggiungere riferimenti a PdQ

### ISSUE THREAD

**Issue by AMike01** [SWEet16-SWE-Group/docs#212]
I riferimenti andranno sicuramente ampliati. 
Ad esempio in #206 giovanni parla di ISO/IEC 9126:2001.
Non che sia una cosa da fare subito, però dobbiamo tenerne conto.

_Originally posted by @AMike01 in https://github.com/SWEet16-SWE-Group/docs/pull/205#discussion_r1523566903_

Manca da aggiungere anche il riferimento al glossario

**Comment by IuliusSignorelli** [comment]
ma tenerne conto in che senso?

**Comment by AMike01** [comment]
> Member

Vanno aggiunti i riferimenti corretti.

**Comment by AMike01** [comment]
> ma tenerne conto in che senso?

Vanno aggiunti i riferimenti corretti.

**Comment by AMike01** [comment]
Aggiungere ISO/IEC 9126:2001: https://www.iso.org/standard/35733.html

**Comment by AMike01** [comment]
Ricordarsi anche di aggiungere riferimento a glossario.
