### ISSUE TITLE
aggiornamento norme di progetto documentazione

### ISSUE THREAD

**Issue by bzn0u95quudr7jutfjap** [SWEet16-SWE-Group/docs#332]
- opzionale rimozione di latex workshop
- aggiunta di hunspell per il rilevamento e correzione degli errori ortografici
- opzionale aggiunta di php per il parsing stilistico dei documenti ( perché lo script di validazione è scritto in php )
- aggiunto il requisito della github action per poter mergiare il ramo in documentazione-main

**Comment by AMike01** [comment]
Non metterei "opzionale rimozione di latex workshop"
